# ローカル開発環境起動
dev:
	pnpm run dev

# Storybookを開く
sb:
	pnpm run sb

# ESLintチェック
lint:
	npx eslint --ext .ts,.tsx,.json,.js,.jsx src/

# 型チェック
tsc:
	npx tsc --noEmit

# テスト
test:
	npm run test

# Scaffdog (コード自動生成)
sd:
	pnpm run scaffdog
